FROM andriykalashnykov/go-face-recognition:latest-builder AS builder

# https://hub.docker.com/_/alpine/tags
FROM alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 AS runtime

WORKDIR /app

COPY --from=builder /app/cmd/main .

COPY --from=builder /app/fonts fonts/
COPY --from=builder /app/images/ images/
COPY --from=builder /app/models/ models/
COPY --from=builder /app/persons/ persons/

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
