version: "3.8"

services:
  app:
    container_name: go-face-recognition
    build:
      context: .
      dockerfile: Dockerfile.dlib-docker-go
    volumes:
      - "./internal:/app/internal"
      - "./images:/app/images"
      - "./persons:/app/persons"
      - "./cmd:/app/cmd"
