FROM ghcr.io/andriykalashnykov/go-face-recognition:v0.0.2-builder AS builder

# https://hub.docker.com/_/alpine/tags
FROM alpine:3.23.0@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375 AS runtime

WORKDIR /app

COPY --from=builder /app/cmd/main .

COPY --from=builder /app/fonts fonts/
COPY --from=builder /app/images/ images/
COPY --from=builder /app/models/ models/
COPY --from=builder /app/persons/ persons/

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
