FROM ghcr.io/andriykalashnykov/go-face-recognition:v0.0.1-builder AS builder

# https://hub.docker.com/_/alpine/tags
FROM alpine:3.22.2@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412 AS runtime

WORKDIR /app

COPY --from=builder /app/cmd/main .

COPY --from=builder /app/fonts fonts/
COPY --from=builder /app/images/ images/
COPY --from=builder /app/models/ models/
COPY --from=builder /app/persons/ persons/

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
